blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf.urls import handler404
from .views import (
    HomeBlogView, 
    CreatePostView, 
    DetailPostView, 
    UpdatePostView, 
    DeletePostView, 
    ProfileUpdateView,
    ProfileListPostsView,
    Error404View
    )

app_name = 'blog'

handler404 = Error404View.as_view()

urlpatterns = [
    path('', HomeBlogView.as_view(), name='home'),
    path('detail/<int:pk>', DetailPostView.as_view(), name='detail'),
    path('delete/<int:pk>', DeletePostView.as_view(), name='delete'),
    path('profile/', login_required(ProfileUpdateView.as_view()), name='profile'),
    path('profile/posts', login_required(ProfileListPostsView.as_view()), name='profile_posts'),
    path('profile/create/post', login_required(CreatePostView.as_view()), name='create'),
    path('profile/update/post/<int:pk>', login_required(UpdatePostView.as_view()), name='update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import blog_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_home, name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path("__reload__/", include("django_browser_reload.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/layouts/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block styles %}{% endblock styles %}
    {% tailwind_css %}
    <link rel="icon" type="image/x-icon" href="{% static 'favicon/foto_blog.png' %}">

    <title>{% block title %}{% endblock title %}</title>
    <script src="https://kit.fontawesome.com/6e08380902.js" crossorigin="anonymous"></script>
</head>
<body class="bg-gray-50">
    {% include 'layouts/partials/navbar.html' %}
    
    <main class="max-w-7xl mx-auto px-4 pt-24 pb-12 flex flex-col lg:flex-row gap-8 min-h-[79.1vh]">
        {% block content %}{% endblock content %}
    </main>

    {% include 'layouts/partials/footer.html' %}
    <script src="{% static 'blog/js/menu.js' %}"></script>
</body>
</html>

templates/layouts/base_login_register.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block styles %}{% endblock styles %}
    {% tailwind_css %}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon/foto_blog.png' %}">
</head>
<body class="bg-gray-50">
    {% block content %}{% endblock content %}
</body>
</html>

templates/layouts/base_profile.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block styles %}{% endblock styles %}
    {% tailwind_css %}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon/foto_blog.png' %}">
    <script src="https://kit.fontawesome.com/6e08380902.js" crossorigin="anonymous"></script>
</head>
<body class="bg-gray-50">
    {% include 'layouts/partials/navbar.html' %}
    
    <main class="max-w-7xl mx-auto px-4 pt-24 pb-12 flex flex-col lg:flex-row">
        <div class="flex flex-col lg:flex-row px-2 items-center">
            <aside class="flex lg:flex-col lg:h-[80.5vh] w-[90vw] md:w-[80vw] lg:w-[35vw] xl:w-[28vw] 2xl:w-[15vw] py-3 bg-[#8181811A] shadow-lg items-center rounded-lg justify-center">
                <div class="w-[9em] mx-1 md:w-[9em] md:h-[50%] flex justify-center items-center">
                    <img src="{{ user.image.url }}" alt="foto de perfil" class="rounded-full">
                </div>
                <div class="w-[65%] lg:h-[50%] flex flex-col mx-1">
                    <div class="py-5">
                        <a id="btn-personal-data" href="{% url 'blog:profile' %}" onclick="changeButtonColor('btn-personal-data')"><p class="font-semibold text-xl md:text-2xl lg:text-3xl py-3">Datos personales</p></a>
                        <hr id="hr-personal-data" class="border-black">
                    </div>
                    <div class="py-5">
                        <a id="btn-personal-posts" href="{% url 'blog:profile_posts' %}" onclick="changeButtonColor('btn-personal-posts')"><p class="font-semibold text-xl md:text-2xl lg:text-3xl py-3">Publicaciones</p></a>
                        <hr id="hr-personal-posts" class="border-black">
                    </div>
                </div>
            </aside>
            {% block content %}{% endblock content %}
        </div>
    </main>
    {% include 'layouts/partials/footer.html' %}
    <script src="{% static 'blog/js/menu.js' %}"></script>
    <script src="{% static 'blog/js/buttonColor.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
</body>
</html>

templates/layouts/error_404.html
{% extends 'layouts/base.html' %}

{% block content %}
    <main class="min-h-[84.7vh]">
        <div class="p-8 flex flex-col justify-center items-center h-[84.7vh] space-y-6">
            <h1 class="text-blue-600 font-bold text-9xl">404</h1>
            <p>La Página Que Estás Buscando No Existe</p>
            <a href="{% url 'blog:home' %}" class="text-blue-600"><-- Volver a página principal</a>
        </div>
    </main>
{% endblock content %}