accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginUserView, LogoutUserView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout')
]

blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf.urls import handler404
from .views import (
    HomeBlogView, 
    CreatePostView, 
    DetailPostView, 
    UpdatePostView, 
    DeletePostView, 
    ProfileUpdateView,
    ProfileListPostsView,
    Error404View
    )

app_name = 'blog'

handler404 = Error404View.as_view()

urlpatterns = [
    path('', HomeBlogView.as_view(), name='home'),
    path('detail/<int:pk>', DetailPostView.as_view(), name='detail'),
    path('delete/<int:pk>', DeletePostView.as_view(), name='delete'),
    path('profile/', login_required(ProfileUpdateView.as_view()), name='profile'),
    path('profile/posts', login_required(ProfileListPostsView.as_view()), name='profile_posts'),
    path('profile/create/post', login_required(CreatePostView.as_view()), name='create'),
    path('profile/update/post/<int:pk>', login_required(UpdatePostView.as_view()), name='update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import blog_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_home, name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path("__reload__/", include("django_browser_reload.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/layouts/partials/aside.html
<aside class="lg:w-1/4">
    <div class="bg-white rounded-xl shadow-md p-6">
        <h2 class="text-2xl font-bold text-gray-800 mb-6">Más Vistos</h2>
        <div class="space-y-6">
            {% for more_view in more_views %}
                <a href="{% url 'blog:detail' more_view.id %}">
                    <div class="flex items-center space-x-4 mb-8">
                        <img src="{{ more_view.image.url }}" alt="Popular Post" class="w-20 h-20 rounded-lg object-cover">
                        <div class="space-y-2 flex flex-col">
                            <h3 class="font-semibold text-gray-800">{{ more_view.title|truncatechars:27 }}</h3>
                            <div class="flex space-x-2 items-center">
                                <div class="flex px-1 text-sm text-gray-600">
                                    <span>Vistas: {{ more_view.get_view_count }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</aside>

templates/layouts/partials/footer.html
<footer class="bg-gray-800 text-white py-12">
    <div class="max-w-7xl mx-auto px-4">
        <div class="grid md:grid-cols-2 lg:grid-cols-2 gap-10">
            <div>
                <h3 class="text-xl font-bold mb-4">Sobre el Blog</h3>
                <p class="text-gray-400">Compartiendo conocimiento y fortaleciendo a los desarrolladores a través de contenido de calidad.</p>
            </div>
            <div>
                <h3 class="text-xl font-bold mb-4">Redes Sociales</h3>
                <div class="flex space-x-4">
                    <a href="https://github.com/JoelRazuri" target="_blank" class="text-gray-400 hover:text-white"><i class="fab fa-github text-2xl"></i></a>
                    <a href="https://www.linkedin.com/in/joelrazuri/" target="_blank" class="text-gray-400 hover:text-white"><i class="fab fa-linkedin text-2xl"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/layouts/partials/navbar.html
{% load static %}
<nav class="bg-white shadow-lg fixed w-full top-0 z-50">
    <div class="max-w-7xl mx-auto px-4">
        <div class="flex justify-between h-16">
            <div class="flex items-center">
               <a href="{%url 'blog:home' %}"><span class="ml-2 font-bold text-xl text-gray-800">CodeBlog</span></a>
            </div>

            <div class="hidden md:flex items-center space-x-4">
                <form class="relative" action="{% url 'blog:home' %}" method="GET">
                    <input name="q" type="text" placeholder="Buscar publicación..." class="w-64 px-4 py-2 rounded-lg bg-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500">
                    <button type="submit"><i class="fas fa-search absolute right-3 top-3 text-gray-400"></i></button>
                </form>
                
                {% if  user.is_authenticated %}
                    <div class="flex text-gray-600">
                        <a href="{%url 'blog:profile' %}"><button class="px-4 py-2  hover:text-gray-800"><i class="fas fa-user mr-2"></i>Perfil</button></a>
                        <form action="{% url 'accounts:logout' %}" method="POST" class="hover:text-gray-800">
                            {% csrf_token %}
                            <input type="submit" value="Cerrar Sesión" class="cursor-pointer px-4 py-2">
                        </form> 
                    </div>      
                {% endif %}
                
                {% if not user.is_authenticated %}
                    <a href="{%url 'accounts:login' %}" class="px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-700"><button >Iniciar Sesión</button></a>
                    <a href="{%url 'accounts:register' %}" class="px-4 py-2 text-blue-600 border border-blue-600 rounded-lg hover:bg-blue-50"><button>Registrarse</button></a>
                {% endif %}
            </div>

            <div class="md:hidden flex items-center">
                <button id="mobile-menu-button" class="text-gray-600 hover:text-gray-800">
                    <i class="fas fa-bars text-2xl"></i>
                </button>
            </div>
        </div>
    </div>

    <div id="mobile-menu" class="hidden md:hidden bg-white pb-4 px-4">
        <div class="flex flex-col space-y-4">
            <form class="relative" action="{% url 'blog:home' %}" method="GET">
                <input name="q" type="text" placeholder="Buscar publicación..." class="px-4 py-2 rounded-lg bg-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 w-[93vw]">
                <button type="submit"><i class="fas fa-search absolute right-3 top-3 text-gray-400"></i></button>
            </form>
            {% if  user.is_authenticated %}
                <div class="text-gray-600">
                    <a href="{%url 'blog:profile' %}"><button class="px-4 py-2 hover:text-gray-800"><i class="fas fa-user mr-2"></i>Perfil</button></a>
                    <form action="{% url 'accounts:logout' %}" method="POST" class="hover:text-gray-800">
                        {% csrf_token %}
                        <input type="submit" value="Cerrar Sesión" class="cursor-pointer px-4 py-2">
                    </form> 
                </div>
                
            {% endif %}

            {% if not user.is_authenticated %}
                <a href="{%url 'accounts:login' %}" class="px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-700"><button >Iniciar Sesión</button></a>
                <a href="{%url 'accounts:register' %}" class="px-4 py-2 text-blue-600 border border-blue-600 rounded-lg hover:bg-blue-50"><button>Registrarse</button></a>
            {% endif %}
        </div>
    </div>
</nav>