blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf.urls import handler404
from .views import (
    HomeBlogView, 
    CreatePostView, 
    DetailPostView, 
    UpdatePostView, 
    DeletePostView, 
    ProfileUpdateView,
    ProfileListPostsView,
    Error404View
    )

app_name = 'blog'

handler404 = Error404View.as_view()

urlpatterns = [
    path('', HomeBlogView.as_view(), name='home'),
    path('detail/<int:pk>', DetailPostView.as_view(), name='detail'),
    path('delete/<int:pk>', DeletePostView.as_view(), name='delete'),
    path('profile/', login_required(ProfileUpdateView.as_view()), name='profile'),
    path('profile/posts', login_required(ProfileListPostsView.as_view()), name='profile_posts'),
    path('profile/create/post', login_required(CreatePostView.as_view()), name='create'),
    path('profile/update/post/<int:pk>', login_required(UpdatePostView.as_view()), name='update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import blog_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_home, name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path("__reload__/", include("django_browser_reload.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from accounts.models import CustomUser
from ckeditor.fields import RichTextField
from django.db import models
from datetime import date


class Post(models.Model):
    title = models.CharField(max_length=80, blank=False, null=False, verbose_name='Título')
    content = RichTextField(blank=False, null=False, verbose_name='Contenido')
    image = models.ImageField(upload_to='post_images/', verbose_name='Imagen')
    created_date = models.DateField(default=date.today, verbose_name='Fecha de creación')
    published = models.BooleanField(default=False)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Autor')

    def __str__(self):
        return self.title
    
    @property
    def get_view_count(self):
        return self.postview_set.count()



class PostView(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    

blog/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'w-full'}),
            'content': forms.Textarea(),
            'image': forms.FileInput(),
        }

blog/views.py
from django.db.models.base import Model as Model
from django.db.models import Count
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from accounts.forms import CustomUserUpdateForm
from accounts.models import CustomUser
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from .forms import PostForm
from .models import Post, PostView
from django.http import HttpResponseRedirect


class HomeBlogView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'  
    paginate_by = 4 

    def get_queryset(self):
        queryset = Post.objects.filter(published=True).order_by('-id')
        search_query = self.request.GET.get('q')
        if search_query:
            queryset = queryset.filter(
                Q(title__icontains=search_query) | Q(author__username__icontains=search_query)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['more_views'] = Post.objects.filter(published=True).annotate(view_count=Count('postview')).order_by('-view_count')[:6]
        return context



class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/create_blog.html'
    success_url = reverse_lazy('blog:profile_posts')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def form_valid(self, form):
        messages.success(self.request, '¡La publicación se ha creado correctamente! Espere a que el administrador la habilite')
        form.instance.author = self.request.user
        return super().form_valid(form)



class DetailPostView(DetailView):
    model = Post
    template_name = 'blog/detail_blog.html'
    context_object_name = 'post'

    def get_object(self, **kwargs):
        post = super().get_object(**kwargs)
        PostView.objects.create(post=post)
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.object.author
        context['more_views'] = Post.objects.filter(published=True).annotate(view_count=Count('postview')).order_by('-view_count')[:6]
        context['related_posts'] = Post.objects.filter(author=author).exclude(pk=self.object.pk).order_by('-id')[:4]
        return context



class UpdatePostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/update_blog.html'
    context_object_name = 'post'
    success_url = reverse_lazy('blog:profile_posts')

    def form_valid(self, form):
        messages.success(self.request, '¡La publicación se ha actualizado correctamente!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Hubo un error al actualizar la publicación. Por favor, inténtalo de nuevo.')
        return super().form_invalid(form)



class DeletePostView(DeleteView):
    model = Post
    template_name = 'blog/delete_blog.html'
    context_object_name = 'post'
    success_url = reverse_lazy('blog:profile_posts')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '¡La publicación se ha eliminado correctamente!')
        return super().delete(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['messages'] = messages.get_messages(self.request)
        return context



class Error404View(TemplateView):
    template_name = 'layouts/error_404.html'



class ProfileUpdateView(UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    template_name = 'blog/profile_user_update.html'
    context_object_name = 'user'
    success_url = reverse_lazy('blog:profile')

    def dispatch(self, request, *args, **kwargs):
       self.object = self.get_object()
       return super().dispatch(request, *args, **kwargs)
    
    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        changes_made = False
        new_image = self.request.FILES.get('image')
        if new_image:
            changes_made = True
        if not changes_made:
            for field in form.changed_data:
                if field != 'image':  
                    changes_made = True
                    break
        if not changes_made:
            messages.info(self.request, '¡No hizo ningún cambio!')
            return self.redirect_to_success()
        user = form.save(commit=False)
        if new_image:
            user.image = new_image 
        user.save()
        messages.success(self.request, '¡Tus datos de perfil se han actualizado correctamente!')
        return super().form_valid(form)

    def redirect_to_success(self):
        return HttpResponseRedirect(self.success_url)
    
    def form_invalid(self, form):
        messages.error(self.request, '¡Hubo un error al actualizar tus datos de perfil. Por favor, inténtalo de nuevo!')
        return super().form_invalid(form)


class ProfileListPostsView(ListView):
    model = Post
    template_name = 'blog/profile_list_posts.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).order_by('-id')

templates/blog/create_blog.html
{% extends 'layouts/base_profile.html' %}

{% block title %}Crear Publicación{% endblock title %}
{% load static %}
{% block content %}
    {% comment %} 
        Con el atributo 'enctype="multipart/form-data"' Debemos indicar en el formulario que vamos a subir un archivo de 
        este modo, o de lo contrario recibiremos un error de validación diciéndonos que el campo está vacío. 
    {% endcomment %}
    <section class="py-5">
        <form action="{% url 'blog:create' %}" method="POST" enctype="multipart/form-data" class="flex flex-col justify-center items-center space-y-6">
            {% csrf_token %}
    
            <div class="w-[90vw] md:w-[80vw] lg:w-1/2">
                {{ form.title.label }}:
                {{ form.title }}
            </div>
            <div class="w-[90vw] md:w-[80vw] lg:w-1/2">
                {{ form.content.label }}:
                {{ form.content }}
            </div>
            <div>
                {{ form.image.label }}:
                {{ form.image }}
            </div>
        
            <button class="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-14 shadow-lg shadow-gray-400 h-[6vh]" type="submit">Agregar</button>
            
        </form>
    </section>
{% endblock content %}

templates/blog/delete_blog.html
{% extends 'layouts/base_profile.html' %} 

{% block title %}Borrado del Post{% endblock title %}
{% load static %}
{% block content %}
<section class="min-h-[84.8vh] px-10 py-8 flex flex-col justify-center items-center">
    <h2 class="text-3xl lg:text-4xl mb-4">Seguro deseas borrar el post "{{ post.title }}"?</h2>
    <div class="flex space-x-5 items-center">
        <a href="{% url 'blog:profile_posts' %}" class="text-xl">Cancelar</a>
        <form action="" method="POST">
            {% csrf_token %}
            <button tpye="submit" class="text-xl bg-red-600 hover:bg-red-700 text-white font-semibold py-3 px-14 shadow-lg shadow-gray-400 h-[6vh]">Borrar</button>
        </form>
    </div>
    
</section>
{% endblock content %}

templates/blog/detail_blog.html
{% extends 'layouts/base.html' %}

{% block title %}Detalle del Publicación{% endblock title %}

{% load static %}
{% block content %}
    <section class="lg:w-3/4">
        <div class="px-10 pb-3">
            <h2 class="font-semibold text-slate-900 text-5xl py-4 mb-2">{{ post.title }}</h2>
            <div class="flex items-center">
                <img src="{{ post.author.image.url }}" alt="foto" class="mr-1 rounded-full h-9 w-9">
                <p>{{ post.author.username | title }} <span class="text-gray-500">| {{ post.created_date }}</span></p>
            </div>
        </div>

        
        <section class="w-[100%] flex flex-col">
            <div class="px-10">
                <img src="{{ post.image.url }}" alt="foto del post" class=" h-[40em] w-full mb-3">
                <div class="text-gray-600">
                    <span><i class="fa-regular fa-eye"></i> {{ post.get_view_count }}</span>  
                </div>
                <div class="text-gray-600">
                    <p class="py-2">{{ post.content | safe }}</p>
                </div>
                <div class="py-5">
                    <hr class=" border-gray-400">
                </div>
            </div>

            <section class="px-10 pb-2">
                <h2 class="py-4 font-semibold text-4xl">Más Publicaciones</h2>
                <div class="flex flex-col lg:flex-row gap-2 items-center">
                    {% for related_post in related_posts  %}
                        <article class="bg-white border-gray-200 border-[1px] rounded-xl shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300 w-60 min-h-[505px]">
                            <img src="{{ related_post.image.url }}" alt="JavaScript Blog Post" class="w-full h-48 object-cover">
                            <div class="p-6">
                                <div class="flex items-center mb-3">
                                    <img src="{{ related_post.author.image.url }}" alt="foto" class="mr-1 rounded-full h-9 w-9">
                                    <p>{{ related_post.author.username | title }} <span class="text-gray-500">| {{ related_post.created_date }}</span></p>
                                </div>
                                <h2 class="text-xl font-bold text-gray-800 mb-1">{{ related_post.title }}</h2>
                                <div class="text-gray-600 mb-5">
                                    <p>{{ related_post.content | safe|truncatechars:48 }}</p>
                                </div>
                                <a href="{% url 'blog:detail' related_post.id %}" class="text-blue-600 hover:text-blue-800 font-semibold">Leer más →</a>
                            </div>
                        </article>
                    {% empty %}
                        <p class="py-3 text-gray-600">No hay posteos relacionados.</p>
                    {% endfor %}
                </div>  
            </section>
        </section>
        
    </section>

        {% include 'layouts/partials/aside.html' %}
{% endblock content %}

templates/blog/index.html
{% extends 'layouts/base.html' %}

{% block title %}Blog{% endblock title %}
{% load static %}
{% block content %}
    <section class="lg:w-3/4">
        <div class="text-center mb-8">
            <h1 class="text-4xl font-bold text-gray-800 mb-4">Bienvenido a CodeBlog</h1>
            <p class="text-xl text-gray-600">Tu fuente diaria de conocimientos sobre programación, tutoriales y noticias tecnológicas.</p>
        </div>

        <div class="grid md:grid-cols-2 lg:grid-cols-2 gap-8">
            {% for post in posts  %}
                <article class="bg-white border-gray-200 border-[1px] rounded-xl shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300">
                    <img src="{{ post.image.url }}" alt="Imagen Post" class="w-full h-48 object-cover">
                    <div class="p-6">
                        <div class="flex items-center mb-3">
                            <img src="{{ post.author.image.url }}" alt="foto" class="mr-1 rounded-full h-9 w-9">
                            <p>{{ post.author.username | title }} <span class="text-gray-500">| {{ post.created_date }}</span></p>
                        </div>
                        <h2 class="text-xl font-bold text-gray-800 mb-1">{{ post.title }}</h2>
                        <div class="text-gray-600 mb-5">
                            <p>{{ post.content | safe|truncatechars:120 }}</p>
                        </div>
                        <a href="{% url 'blog:detail' post.id %}" class="text-blue-600 hover:text-blue-800 font-semibold">Leer más →</a>
                    </div>
                </article>
            {% endfor %}
        </div>

        <div class="flex justify-center items-center space-x-2 mt-12">
            {% if page_obj.has_previous %}
                <a href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}" class="px-4 py-2 rounded-lg bg-gray-200 text-gray-600 hover:bg-gray-300">
                    <i class="fas fa-chevron-left mr-2"></i>Anterior
                </a>
            {% endif %}
            
            {% if page_obj.paginator.num_pages != 1 %}
                <span>
                    {{ page_obj.number }} ... {{ page_obj.paginator.num_pages }}
                </span>
            {% endif %}
            
            {% if page_obj.has_next %}
                <a href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}" class="px-4 py-2 rounded-lg bg-gray-200 text-gray-600 hover:bg-gray-300">
                    Siguiente<i class="fas fa-chevron-right ml-2"></i>
                </a>
            {% endif %}
        </div>
    </section>

    {% include 'layouts/partials/aside.html' %}
{% endblock content %}

templates/blog/profile_list_posts.html
{% extends 'layouts/base_profile.html' %}
{% block title %}Publicaciones {% endblock title %}
{% load static %}
{% block content %}
    <section class="h-[84.8vh] py-8 px-10 overflow-y-auto">
        <div class="flex space-x-4">
            <a href="{% url 'blog:create' %}" class="max-h-12 text-white bg-blue-600 rounded-lg hover:bg-blue-700 py-3 px-4 shadow-lg">Crear publicación</a>
            <div class="flex justify-center">
                {% if messages %}
                    {% for message in messages %}
                        <div class="py-2 px-4 mb-4 rounded-lg {% if message.tags == 'error' %}bg-red-200 text-red-800{% elif message.tags == 'success' %} bg-green-200 text-green-800{% endif %}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="xl:grid xl:grid-cols-2 gap-6 mt-5 w-96 xl:w-auto">
            {% for post in posts  %}
                <article class="bg-slate-50 flex shadow-lg h-28 justify-between mb-2">
                    <div class="flex">
                        <img src="{{ post.image.url }}" alt="" width="100" class="p-2 object-cover">
                        <div class=" m-2">
                            <h4 class="w-full pt-1 pb-2 font-bold">{{ post.title|truncatechars:16 }}</h4>
                            <div class="flex space-x-3 mt-3 items-center">
                                <img src="{{ user.image.url }}" alt="" class="rounded-full h-10 w-10">
                                <div class="text-sm md:text-base">
                                    <p>{{ post.author | title }}</p>
                                    <p>{{ post.created_date }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="flex flex-col m-2 justify-around text-sm md:text-base">
                        <a href="{% url 'blog:detail' post.id %}" class="font-semibold">Ver</a>
                        <a href="{% url 'blog:update' post.id %}" class="text-[#169D00] font-semibold">Editar</a>
                        <a href="{% url 'blog:delete' post.id %}" class="text-[#ED0000] font-semibold">Eliminar</a>
                    </div> 
                </article>
            {% endfor %}
        </div>
    </section>
{% endblock content %}

templates/blog/profile_user_update.html
{% extends 'layouts/base_profile.html' %}
{% load static %}
{% block title %}Perfil{% endblock title %}
{% block content %}
    <section class="md:h-[84.8vh] w-full md:w-[75%] py-5">
        <form action="{% url "blog:profile" %}" method="POST" enctype="multipart/form-data" class="h-[100%]">
            {% csrf_token %}
            <div class="md:h-[50%] md:grid md:grid-cols-2 p-10">
                <div class="flex flex-col w-96">
                    <label for="">Nombre:</label>
                    {{ form.first_name }}
                </div>
                <div class="flex flex-col w-96">
                    <label for="">Apellido:</label>
                    {{ form.last_name }}
                </div>
                <div class="flex flex-col w-96">
                    <label for="">Email:</label>
                    {{ form.email }}
                </div>
                <div class="content-admin flex flex-col w-96">
                    <label for="">Usuario:</label>
                    <input type="text" value="{{ user.username }}" disabled class="text-slate-500 cursor-not-allowed w-1/2"> 
                </div>
                <div class="flex flex-col w-96">
                    <label for="">Contraseña:</label>
                    {{ form.new_password1 }}
                </div>
                <div class="flex flex-col w-96">
                    <label for="">Repetir contraseña:</label>
                    {{ form.new_password2 }}
                </div>
                <div class="flex flex-col w-96">
                    <label for="">Foto de perfil:</label>
                    {{ form.image }}
                </div>
            </div>
            <div class="flex justify-center">
                {% if messages %}
                    {% for message in messages %}
                        <div class="py-2 px-4 mb-1 rounded-lg {% if message.tags == 'error' %}bg-red-200 text-red-800{% elif message.tags == 'success' %} bg-green-200 text-green-800{% elif message.tags == 'info' %} bg-yellow-200 text-yellow-700{% endif %}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="flex mt-4 justify-center items-center">
                <button class="text-white bg-blue-600 rounded-lg hover:bg-blue-700 font-semibold py-3 px-14 shadow-lg shadow-gray-400 h-[6vh]" type="submit">Modificar</button>
            </div>
        </form>
    </section>
{% endblock content %}

templates/blog/update_blog.html
{% extends 'layouts/base_profile.html' %}

{% block title %}Actualizar Publicación{% endblock title %}
{% load static %}
{% block content %}
    <section class="py-5">
        <form action="{% url 'blog:update' post.id %}" method="POST" enctype="multipart/form-data" class="flex flex-col justify-center items-center space-y-3">
            {% csrf_token %}
            
            <div class="w-[90vw] md:w-[80vw] lg:w-1/2">
                {{ form.title.label }}:
                {{ form.title }}
            </div>

            <div class="w-[90vw] md:w-[80vw] lg:w-1/2">
                {{ form.content.label }}:
                {{ form.content }}
            </div>
            
            <div class="flex self-start lg:self-center w-[27.1em]">
                <label for="" class="mr-2">Actual:</label>
                <img src="{{ post.image.url }}" alt="" width="100px">
            </div>

            <div class="self-start lg:self-center">
                <label for="" class="mr-1">Cambiar:</label>
                {{ form.image }}
            </div>
            
            
           
            <button class="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-14 shadow-lg shadow-gray-400 h-[6vh]" type="submit">Actualizar</button>
           
        </form>
    </section>
{% endblock content %}